name: on-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    name: lint and test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install deps
        run: npm ci

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: lint
        run: npm run lint

      - name: test
        if: runner.os != 'Linux'
        run: npm run test

      - name: compile
        if: runner.os != 'Linux'
        run: npm run compile
