name: on-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    name: lint and test
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
